### ISSUE TITLE
Edit contacts, tags and assets

### ISSUE THREAD

**Issue by bryanyee33** [AY2324S2-CS2103T-W12-3/tp#13]
As a user, I can edit contacts, tags and assets, so that I can change details without recreating contacts, as there are too many details to re-add.

**Comment by darkvoid32** [comment]
Add new edit command to edit assets, we will have 2 edit commands after this issue, `edit` and `edita`.

`edit <id> [--email <email> --phone <phone no.> [--tag <tag name> [<tag name>]...]] | [--location <location>]`
`edita <curr_name> [--name newname] [--location newlocation]`
