### ISSUE TITLE
Jar filename in Quick Start of UG does not match actual filename in releases

### ISSUE THREAD

**Issue by aureliony** [AY2324S2-CS2103T-W12-3/tp#132]
`assetbook.jar` should be `assetbook-3.jar`.

> Download the latest assetbook.jar from [here](https://github.com/AY2324S2-CS2103T-W12-3/tp/releases).

**Comment by aureliony** [comment]
Another line that also has a mismatch

> use the java -jar assetbook.jar command to run the application

**Comment by yisiox** [comment]
Noted will fix as part of #127
