### ISSUE TITLE
[PE-D][Tester B] Commands are not Case-sensitive

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W12-3/tp#212]
To the best of my knowledge, the UG does not mention that the command words are case-insensitive. However, in the application it is. As shown by ADD command being able to execute. This can be easily fixed by updating the UG. 

![image.png](https://raw.githubusercontent.com/Austintjh19/ped/main/files/d789b17c-a4de-4bc8-8c2a-42f517aea9ff.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Austintjh19/ped#9

**Comment by aureliony** [comment]
This is a documentation bug.
We should add a note stating that the first word of commands are case-insensitive.
