### ISSUE TITLE
[PE-D][Tester B] Inconsistent limitations for the domain of Email 

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W12-3/tp#215]
The applicaiton currently allows `.` in domain label for email despite the instruction stating that it only allows alphanumeric characters, separated by hyphens only. 

![image.png](https://raw.githubusercontent.com/Austintjh19/ped/main/files/5e79950d-015e-4a54-8c0c-5124b462d252.png)

![image.png](https://raw.githubusercontent.com/Austintjh19/ped/main/files/717dbc25-ed78-479c-ab0f-a13ad31e63be.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Austintjh19/ped#10

**Comment by aureliony** [comment]
Seems like you misinterpreted the error message. As stated, `The domain name is made up of domain labels separated by periods.`
In your example, there are three domain labels: `u`, `nus` and `edu`. These are all separated by periods and hence `u.nus.edu` is a valid domain name.
