### ISSUE TITLE
[PE-D][Tester E] UI display text is missing a space

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W12-3/tp#221]
## Reference Screenshot - Invalid asset command
![Screenshot 2024-04-05 165604.png](https://raw.githubusercontent.com/triciiaaa/ped/main/files/a3f9aa05-aed2-4270-af37-4beb8e74deaf.png)

## Reference Screenshot - Adding invalid tag
![Screenshot 2024-04-05 172311.png](https://raw.githubusercontent.com/triciiaaa/ped/main/files/056962df-3b7b-45ba-a533-5126c814b00a.png)

## Description
As I was keying in an invalid asset command, the error message shown seemed to be missing a space between the words. On a separate occasion, as I was keying in adding an invalid tag to a contact, the error message shown seemed to be missing a space between the words. 

## Possible Solution
Perhaps it would be good to double-check how the error messages are displayed to the users.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: triciiaaa/ped#9

**Comment by aureliony** [comment]
To add a period and newline.
