### ISSUE TITLE
[PE-D][Tester E] Weak validation on email domain

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W12-3/tp#227]
## Reference Screenshot - Weak validation on email domain
![Screenshot 2024-04-05 172003.png](https://raw.githubusercontent.com/triciiaaa/ped/main/files/9a815bc2-7a2e-4ecf-8d10-d22321465773.png)

## Description
While the User Guide specifies that the email field should contain the format ‘local-part@domain', I am able to key in jd@gmail` which is possibly an incorrect domain. Perhaps it would be good to add stronger validation for valid domains used.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: triciiaaa/ped#11

**Comment by aureliony** [comment]
`jd@gmail` is a valid email format. 

See: https://stackoverflow.com/questions/20573488/why-does-html5-form-validation-allow-emails-without-a-dot

**Comment by aureliony** [comment]
We should add a note to the UG to point out this special case.
