### ISSUE TITLE
[PE-D][Tester A] Database of Asset is unclear

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W12-3/tp#236]
In the description of the asset field, it is stated that "Assets must have unique names. If the asset already exists in the database, the existing
asset will be linked instead of a new asset."

It may not be clear as to what the database refers to. Is it the database within the app itself, or is it linked to some online database? 

Among non-technical users, which the UG should be targeting, it is possible that they are unfamiliar with the "database" term, and this could confuse them.

In addition, this was the only instance the term "database" was used in the UG, with no clarification.

![image.png](https://raw.githubusercontent.com/Apzure/ped/main/files/73deac42-b2d1-4efa-87a5-e8f16c6111a2.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: Apzure/ped#12

**Comment by aureliony** [comment]
Solution: change "database" to "JSON file".

**Comment by yisiox** [comment]
> Solution: change "database" to "JSON file".

A more straightforward solution may be to omit this altogether, i.e.

> If the asset already exists...
