### ISSUE TITLE
Short forms for commands

### ISSUE THREAD

**Issue by aureliony** [AY2324S2-CS2103T-W12-3/tp#68]
As a user, I can use short forms for commands such as `a` instead of `add`, to improve my typing efficiency and productivity.

**Comment by aureliony** [comment]
Bumped to `Priority.High`. This falls under overzealous input validation which is considered a `type.FeatureFlaw`.

![image](https://github.com/AY2324S2-CS2103T-W12-3/tp/assets/39163684/d9164e55-a229-4def-9f13-9772822f8d62)

**Comment by yisiox** [comment]
`add`: any prefix
`edit`: any prefix
`asset`: `A`, any prefix otherwise
`undo`: any prefix
`redo`: any prefix
`find`: any prefix
`delete`: any prefix
`exit`: should be deliberate

**Comment by aureliony** [comment]
Planned for future development.
